openapi: 3.0.3
info:
  title: PraFazê! Seu app de tarefas
  version: "1.0"
externalDocs:
  description: Mais informações sobre o projeto no notion
  url: https://www.notion.so/Desafio-Pr-tico-Back-end-47d59d4b2ab741cebf9fb0490afb900a
tags:
  - name: Tarefa
    description: Tudo envolvendo tarefas
paths:
  /tarefa:
    post:
      tags:
        - Tarefa
      summary: Adiciona uma nova tarefa
      description: Adiciona uma nova tarefa
      operationId: addTarefa
      requestBody:
        description: Criar uma nova tarefa
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTarefaDto'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TarefaEntity'
        '400':
          description: Invalid input
    get:
      tags:
        - Tarefa
      summary: Achar todas as tarefas
      description: Achar todas as tarefas
      operationId: findAllTarefa
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/TarefaEntity'
  /tarefa/{tarefaId}:
    get:
      tags:
        - Tarefa
      summary: Achar tarefa pelo ID
      description: Retorna uma única tarefa
      operationId: getTarefaById
      parameters:
        - name: tarefaId
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TarefaEntity'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Tarefa not found
    patch:
      tags: 
        - Tarefa
      summary: Atualiza uma tarefa existente
      description: Atualiza uma tarefa existente pelo seu ID
      operationId: updateTarefa
      parameters:
        - name: tarefaId
          in: path
          description: ID da tarefa a ser deletada
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Atualizar uma tarefa
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTarefaDto'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TarefaEntity'
        '400':
          description: Invalid input
        '404':
          description: Tarefa not found
    delete:
      tags:
        - Tarefa
      summary: Deleta uma tarefa
      description: Deleta uma tarefa pelo seu ID
      operationId: deleteTarefa
      parameters:
        - name: tarefaId
          in: path
          description: ID da tarefa a ser deletada
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TarefaEntity'
        '404':
          description: Tarefa not found
components:
  schemas:
    TarefaEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        nome:
          type: string
          example: "Finalizar o projeto"
        isActive:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CreateTarefaDto:
      type: object
      properties:
        nome:
          type: string
          example: "Fazer o projeto"
    UpdateTarefaDto:
      type: object
      properties:
        nome:
          type: string
          example: "Finalizar o projeto"
        isActive:
          type: boolean
